### ISSUE TITLE
Ne prikazuju se na Horizontalni skroler  u Kapitalu

### ISSUE THREAD

**Issue by nermina** [aldinezi/akta#1]
Ne prikazuje se horizontalni scroller na preview u Kapitalu

**Comment by aldinezi** [comment]
Izmjene na HTML kodu, nisu automatski vidljive na našem testnom serveru, pošto se ne sinkroniziraju sa našim serverom. I lokalnim otvaranjem html fajla, vidljivo je da skroler na novoj poziciji.
