### ISSUE TITLE
prikaz na firefoxu

### ISSUE THREAD

**Issue by nermina** [aldinezi/akta#2]
![image](https://cloud.githubusercontent.com/assets/479269/21981116/37e83b22-dbe6-11e6-92a1-dc85ae155d9f.png)

**Comment by nermina** [comment]
![image](https://cloud.githubusercontent.com/assets/479269/21981168/714546a8-dbe6-11e6-8d43-7fd4ed2fd478.png)
nedostaje placeholder za datume

**Comment by aldinezi** [comment]
Fixed

**Comment by nermina** [comment]
hvala
