### ISSUE TITLE
Implemetacija

### ISSUE THREAD

**Issue by nermina** [aldinezi/akta#4]
Da li mi možete pomoći oko ovog problema prilikom implementacije:
![image](https://cloud.githubusercontent.com/assets/479269/22826928/58f5cfb0-ef95-11e6-8cca-f5f8d2c7011e.png)
![image](https://cloud.githubusercontent.com/assets/479269/22826938/67d2ddd4-ef95-11e6-98ed-a86480ad180e.png)

**Comment by nermina** [comment]
![image](https://cloud.githubusercontent.com/assets/479269/22829261/ffa24742-efa1-11e6-972d-f943e353c7d6.png)

fontovi su u folderu

![image](https://cloud.githubusercontent.com/assets/479269/22829302/372e5872-efa2-11e6-915c-e02db97aef73.png)

**Comment by nermina** [comment]
imam mali problem sa carouselom vjerovatno zbog dužine naslova
![image](https://cloud.githubusercontent.com/assets/479269/22883604/36f0adb4-f1f1-11e6-9314-03778fe65ffb.png)

**Comment by aldinezi** [comment]
Vidim u čemu je problem, možemo ga riješiti. Ali bi dobro bilo konsultirati dizajnera i možda odlučiti da se prikazuje samo po jedna vijest na skroleru, upravo zbog dužine naslova.

**Comment by nermina** [comment]
![image](https://cloud.githubusercontent.com/assets/479269/22883809/44fa842e-f1f2-11e6-8c79-7b23a2e0f498.png)
Da li je ovo zbog dužine naslova

**Comment by nermina** [comment]
kad se smanji rezolucija na 70% skroller izgleda 
![image](https://cloud.githubusercontent.com/assets/479269/22883974/e1f133a4-f1f2-11e6-8baa-6832d6826aa0.png)

**Comment by nermina** [comment]
![image](https://cloud.githubusercontent.com/assets/479269/22884036/15de87de-f1f3-11e6-80f5-87d9eac4c2dc.png)
ili poveća preko 100%

**Comment by aldinezi** [comment]
Da, pošto je predviđeno da tu stanu dva naslova, a na manjim ekranima samo jedan. Također, postojala je greška u tome što se funkcija ovog skrolera pokretala prilikom promjene veličine prozora. Sada je vraćeno da funkcija se pokreće samo prvi puta, na documentready događaj. Tako da ukoliko je smanjen prozor, potrebno je uraditi ponovno učitavanje.
